apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/01
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: claim1
    namespace: 3scale
