apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0004
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /tmp/04
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: claim4
    namespace: 3scale
